name: release

on:
  push:
    branches:
      - main
    tags:
      - "!*"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: cache poetry installation
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-1.2.1

      - name: install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

  release:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["core"]
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: ""
          filters: |
            src:
              - './${{ matrix.package }}/**'

      - name: install dependencies
        # if: steps.changes.outputs.src == 'true'
        run: poetry install --no-interaction --no-root
        working-directory: ./${{ matrix.package }}

      - name: install project dependencies
        # if: steps.changes.outputs.src == 'true'
        run: poetry install --no-interaction
        working-directory: ./${{ matrix.package }}

      - name: test
        # if: steps.changes.outputs.src == 'true'
        run: poetry run pytest -p no:sugar
        working-directory: ./${{ matrix.package }}

      - name: publish
        # if: steps.changes.outputs.src == 'true'
        run: "poetry publish --build --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}"
        working-directory: ./${{ matrix.package }}
